voice_node:
  ros__parameters:

    # Modelos
    recognizer_model: "models/vosk-model-small-pt-0.3"
    voice_model: "models/pt_BR-jeff-medium.onnx"
    voice_config: "models/pt_BR-jeff-medium.onnx.json"

    # Áudios
    voice_files: "voiceFiles"

    # Áudio
    device_index: 4
    audio_frequency: 48000
    buffer_size: 4096

    # Vocabulário
    audio_vocabulary:
      - "clima"
      - "horas"
      - "bom dia"
      - "desligar"
      - "sabedoria"
      - "[unk]"